name: Labeler

on:
  push:
    branches:
      - main

permissions:
  actions: read
  contents: read
  security-events: write
  pull-requests: write

jobs:

  dump-context:
    runs-on: ubuntu-latest
    steps:
      - name: Dump context "GitHub"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

  labeler:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v5
      - name: Run Labeler
        uses: crazy-max/ghaction-github-labeler@v5.3.0
        with:
          skip-delete: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
